# Generated by Django 2.0 on 2018-01-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171222_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=220)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Document')),
            ],
        ),
    ]
